/** 系统异常 */
const CODE_SYS_ERROR = 1010080099 // "系统异常，请联系管理员"
const USER_TOKEN_IS_UNVALID = 1010070010 //"token验证失败"
const USER_ID_IS_NULL = 1010070014 //"用户ID不能为空"

/**发送短信验证码时异常*/

/**手机短信发送成功*/
const SMS_SEND_SUCCESS = 1010070009 // "短信验证码发送成功") ,
/** 手机号码不能为空 */
const MOBILE_IS_UNVALID = 1010070004 // "手机号码校验非法"),
/** 短信发送失败*/
const SMS_SEND_FAILED = 1010070005 // "短信发送失败，请重新获取验证码"

/**获取用户最新信息时异常*/

/** 用户不存在*/
const USER_NOT_FOUND = 1010070001 //"用户不存在") 
/** 用户被锁定*/
const USER_IS_LOCKED = 1010070002 //"用户被冻结，请联系客服"
/** token不能为空*/
const TOKEN_IS_NULL = 1010070003 //"token不能为空"

/** 短信验证码验证超过五次，需要重新获取验证码 */
const VERIFY_CODE_FIVE_TIMES = 1010070006 //"验证超过五次，请重新获取验证码"),
/** 短信验证码错误 */
const VERIFY_CODE_IS_WRONG = 1010070007 //"验证码错误"),
/** 短信验证码失效 */
const VERIFY_CODE_IS_INVALID = 1010070008 //验证码失效,请重新获取验证码"),

/** 未缴纳押金*/
const ACCOUNT_DEPOSIT_IS_NULL = 1010060001 //未缴纳押金，请先缴纳押金"),
/** 账户余额不足 */
const ACCOUNT_IS_NOT_ENOUGH = 1010060002 //余额不足1元，请先充值"),
/** 用户正在开柜，不能再次进行开柜操作 */
const USER_IS_OPENING_GRID = 1010050001 //用户正在开柜，不能再次进行开柜操作"),

const BORROWING_COUNT_OVER_10 = 1010050002 //在借图书超过10本，开锁失败"),

const BORROWING_IS_NOT_IN_CURRENT_GRID = 1010050003 //在借图书不在当前书格中，开锁失败"),

const BOOKSHELF_IS_UNDER_DAMAGE = 1010050004 //当前书柜处理报修状态，不能使用"),

const BOOKSHELF_IS_NOT_EXISTS = 1010050005 //"当前书柜不存在"),

const BOOKSHELF_IS_UNAVAILABLE = 1010050006 //"当前书柜不可用"),

const constBOOK_GRID_IS_NOT_EXISTS = 1010050007 //"当前书格不存在"),

const BOOK_GRID_IS_UNDER_DAMAGE = 1010050008 // "当前书格已报修"),

const BOOK_GRID_IS_UNDER_NON_CLOSED = 1010050009 //"当前书格处于非关闭状态"),

const BOOK_GRID_IS_UNAVAILABLE = 1010050010 // "当前书格不可用"),

const BOOK_GRID_IS_UNDER_NON_INVENTORY = 1010050011 //"当前书格处于非盘点成功状态，不能进行再次盘点"),

const BOOK_GRID_FINALLY_USED_NON_OWN = 1010050012 // "书格最后一次操作并非本人，不能进行再次盘点"),

const BOOK_GRID_LAST_USED_NOT_THIS = 1010050013 // "您最后开启的并非是该书格，不能进行再次盘点"),

const BOOK_GRID_OVER_5_MINUTES = 1010050014 // "距离你最后操作该书格超过5分钟，不能进行再次盘点"),

const BOOK_SHELF_IS_OPEN = 1010050015 // "当前书柜正在有人使用，请稍后再使用"),
/** 查询记录为空 */
const QUERY_LIST_IS_NULL = 1010080002 // "查询记录为空 "),

const PARAM_CHECK_IS_NULL = 1010080001 // "请求参数[%s]不能为空"),
/** %s 不存在 */
const OBJ_NOT_FOUND = 1010080003 // "对象[%s]不存在") ,

const BOOK_GRID_STATUS_IS_NON_OPENED = 1010050015 //"书格当前状态为非打开状态，请刷新后再操作"),

const BOOK_GRID_STATUS_IS_NON_CLOSED = 1010050016 //"书格当前状态为非关闭状态，请刷新后再操作"),

const BOOK_GRID_CANNOT_BE_REPORTED = 1010050017 //"该书格由本人已经报修两次，不能再次报修该书格"),

const BOOK_SHELF_HAS_BEAN_REPORTED = 1010050018 //"该书柜由本人已经报修过，不能再次报修，请联系客服"),
/** 书格相关错误码 */

const ACTIVE_DATAVER_IS_INVALID = 1010080004 //"datever字段不合法，目前只能为1"),

const ACTIVE_DEVICETOEKN_IS_NOT_EXISTS = 1010080005 // "devicetoken不存在"),

const ACTIVE_DATA_IS_INVALID = 1010080006 //"激活时传递的数据不正确，解密失败"),

const ACTIVE_DATA_IS_ARRAY = 1010080007 //"激活时传递的数据不正确，解密成数组"),

const QRCODE_ANALYSIS_IS_WRONG = 1010080008 //"该二维码解析不正确，请重新扫码"),

const REQUEST_CHECK_FAILURE = 1010080009 //"该请求验签失败"),

const CALL_ALIPAY_ERROR = 1010060003 //"调用支付宝接口异常"),

const CALL_ALIPAY_REFUND_ERROR = 1010060004 //"调用支付宝退款接口异常"),

const REFUND_CASH_IS_LT_ZERO = 1010060005 // "余额为负，不能进行退款"),

const REFUND_CAN_NOT = 1010060006 // "当前有在借图书，不能进行退款"),

const REFUND_AUDIT_STATUS_INVALID = 1010060007 //"该笔交易不处于准备退款阶段，请重新提交退款申请"),
const REFUND_NO_DEPOSIT = 1010060008 //"用户无押金可退"),
const REFUND_HAS_SUBMITTED = 1010060009 //"您的退款申请已提交"),
const REFUND_IS_REFUSED = 1010060010 //"您的退款申请被拒绝，请联系客服"),
const REFUND_AUDIT_SUCCESS = 1010060011 //"您的退款审核已经成功"),

const REFUND_AUDDIT_NOT_PASSED = 1010060013 //"该笔交易还未通过退款审核"),
const REFUND_AUDDIT_FAILED = 1010060014 //"该笔交易退款失败"),
const REFUND_AUDDIT_REFUSED = 1010060015 // "该笔交易退款审核被拒绝"),
const REFUND_SUCCESS = 1010060016 // "该笔交易已退款成功"),

const WX_GET_OPENID_FAILED = 1010060012 // "获取openId失败，请联系管理员"),

const ISBN_AND_IS_BOTH_NULL = 1010020001 // "isbn或id不能都为空"),

const SHELF_CODE_IS_BOTH_NULL = 1010020002 // "shelf_code或其他参数不能同时为空"),

const STAFF_LOGIN_NAME_OR_PWD_IS_EMPTY = 4 // "登陆用户名或密码不能为空"),
const STAFF_LOGIN_PWD_IS_INVALID = 2 //"密码不匹配"),
const STAFF_LOGIN_NAME_IS_INVALID = 1 // "账户名输入错误"),
const STAFF_TRANS_IS_NOT_EXISTS = 3 // "该条记录不存在"),

const HAS_NOT_PUTON_BOOK = 40 // "没有新的上架图书"),

const BOOK_INFO_NOT_EXISTS = 2 // "图书信息不存在"),

const BOOK_COMMENTS_OVER_500 = 1010030001 // "评论字数超过500字，不能保存"),

const CARD_CHARGE_CODE_IS_WRONG = 1010070011 //"充值码错误，请重新输入"),
const CARD_CHARGE_IS_INVAILD = 1010070012 // "充值码已失效"),
const CARD_CHARGE_IS_USED = 1010070013 // "您已经使用过该充值码，不能再次使用"),
const USERID_IS_EMPTY = 1010070014 // "该家庭成员不属于当前用户，不能进行修改");
const USER_IS_NOT_SUITED = 1010070015 // "该家庭成员不属于当前用户，不能进行修改");



module.exports = {
    CODE_SYS_ERROR: CODE_SYS_ERROR,

    USER_TOKEN_IS_UNVALID: USER_TOKEN_IS_UNVALID,

    USER_ID_IS_NULL: USER_ID_IS_NULL,

    SMS_SEND_SUCCESS: SMS_SEND_SUCCESS,

    MOBILE_IS_UNVALID: MOBILE_IS_UNVALID,

    SMS_SEND_FAILED: SMS_SEND_FAILED,

    USER_NOT_FOUND: USER_NOT_FOUND,

    USER_IS_LOCKED: USER_IS_LOCKED,

    TOKEN_IS_NULL: TOKEN_IS_NULL,

    VERIFY_CODE_FIVE_TIMES: VERIFY_CODE_FIVE_TIMES,

    VERIFY_CODE_IS_WRONG: VERIFY_CODE_IS_WRONG,

    VERIFY_CODE_IS_INVALID: VERIFY_CODE_IS_INVALID,

    ACCOUNT_DEPOSIT_IS_NULL: ACCOUNT_DEPOSIT_IS_NULL,

    ACCOUNT_IS_NOT_ENOUGH: ACCOUNT_IS_NOT_ENOUGH,

    USER_IS_OPENING_GRID: USER_IS_OPENING_GRID,

    BORROWING_COUNT_OVER_10: BORROWING_COUNT_OVER_10,

    BORROWING_IS_NOT_IN_CURRENT_GRID: BORROWING_IS_NOT_IN_CURRENT_GRID,

    BOOKSHELF_IS_UNDER_DAMAGE: BOOKSHELF_IS_UNDER_DAMAGE,

    BOOKSHELF_IS_NOT_EXISTS: BOOKSHELF_IS_NOT_EXISTS,

    BOOKSHELF_IS_UNAVAILABLE: BOOKSHELF_IS_UNAVAILABLE,

    constBOOK_GRID_IS_NOT_EXISTS: constBOOK_GRID_IS_NOT_EXISTS,

    BOOK_GRID_IS_UNDER_DAMAGE: BOOK_GRID_IS_UNDER_DAMAGE,

    BOOK_GRID_IS_UNDER_NON_CLOSED: BOOK_GRID_IS_UNDER_NON_CLOSED,

    BOOK_GRID_IS_UNAVAILABLE: BOOK_GRID_IS_UNAVAILABLE,

    BOOK_GRID_IS_UNDER_NON_INVENTORY: BOOK_GRID_IS_UNDER_NON_INVENTORY,

    BOOK_GRID_FINALLY_USED_NON_OWN: BOOK_GRID_FINALLY_USED_NON_OWN,

    BOOK_GRID_LAST_USED_NOT_THIS: BOOK_GRID_LAST_USED_NOT_THIS,

    BOOK_GRID_OVER_5_MINUTES: BOOK_GRID_OVER_5_MINUTES,

    BOOK_SHELF_IS_OPEN: BOOK_SHELF_IS_OPEN,

    QUERY_LIST_IS_NULL: QUERY_LIST_IS_NULL,

    PARAM_CHECK_IS_NULL: PARAM_CHECK_IS_NULL,

    OBJ_NOT_FOUND: OBJ_NOT_FOUND,

    BOOK_GRID_STATUS_IS_NON_OPENED: BOOK_GRID_STATUS_IS_NON_OPENED,

    BOOK_GRID_STATUS_IS_NON_CLOSED: BOOK_GRID_STATUS_IS_NON_CLOSED,

    BOOK_GRID_CANNOT_BE_REPORTED: BOOK_GRID_CANNOT_BE_REPORTED,

    BOOK_SHELF_HAS_BEAN_REPORTED: BOOK_SHELF_HAS_BEAN_REPORTED,

    ACTIVE_DATAVER_IS_INVALID: ACTIVE_DATAVER_IS_INVALID,

    ACTIVE_DEVICETOEKN_IS_NOT_EXISTS: ACTIVE_DEVICETOEKN_IS_NOT_EXISTS,

    ACTIVE_DATA_IS_INVALID: ACTIVE_DATA_IS_INVALID,

    ACTIVE_DATA_IS_ARRAY: ACTIVE_DATA_IS_ARRAY,

    QRCODE_ANALYSIS_IS_WRONG: QRCODE_ANALYSIS_IS_WRONG,

    REQUEST_CHECK_FAILURE: REQUEST_CHECK_FAILURE,

    CALL_ALIPAY_ERROR: CALL_ALIPAY_ERROR,

    CALL_ALIPAY_REFUND_ERROR: CALL_ALIPAY_REFUND_ERROR,

    REFUND_CASH_IS_LT_ZERO: REFUND_CASH_IS_LT_ZERO,

    REFUND_CAN_NOT: REFUND_CAN_NOT,

    REFUND_AUDIT_STATUS_INVALID: REFUND_AUDIT_STATUS_INVALID,

    REFUND_NO_DEPOSIT: REFUND_NO_DEPOSIT,

    REFUND_HAS_SUBMITTED: REFUND_HAS_SUBMITTED,

    REFUND_IS_REFUSED: REFUND_IS_REFUSED,

    REFUND_AUDIT_SUCCESS: REFUND_AUDIT_SUCCESS,

    REFUND_AUDDIT_NOT_PASSED: REFUND_AUDDIT_NOT_PASSED,

    REFUND_AUDDIT_FAILED: REFUND_AUDDIT_FAILED,

    REFUND_AUDDIT_REFUSED: REFUND_AUDDIT_REFUSED,

    REFUND_SUCCESS: REFUND_SUCCESS,

    WX_GET_OPENID_FAILED: WX_GET_OPENID_FAILED,

    ISBN_AND_IS_BOTH_NULL: ISBN_AND_IS_BOTH_NULL,

    SHELF_CODE_IS_BOTH_NULL: SHELF_CODE_IS_BOTH_NULL,

    STAFF_LOGIN_NAME_OR_PWD_IS_EMPTY: STAFF_LOGIN_NAME_OR_PWD_IS_EMPTY,

    STAFF_LOGIN_PWD_IS_INVALID: STAFF_LOGIN_PWD_IS_INVALID,

    STAFF_LOGIN_NAME_IS_INVALID: STAFF_LOGIN_NAME_IS_INVALID,

    STAFF_TRANS_IS_NOT_EXISTS: STAFF_TRANS_IS_NOT_EXISTS,

    HAS_NOT_PUTON_BOOK: HAS_NOT_PUTON_BOOK,

    BOOK_INFO_NOT_EXISTS: BOOK_INFO_NOT_EXISTS,

    BOOK_COMMENTS_OVER_500: BOOK_COMMENTS_OVER_500,

    CARD_CHARGE_CODE_IS_WRONG: CARD_CHARGE_CODE_IS_WRONG,

    CARD_CHARGE_IS_INVAILD: CARD_CHARGE_IS_INVAILD,

    CARD_CHARGE_IS_USED: CARD_CHARGE_IS_USED,

    USER_IS_NOT_SUITED: USER_IS_NOT_SUITED,

    USERID_IS_EMPTY: USERID_IS_EMPTY

}